### ISSUE TITLE
CSRF Token in Login

### ISSUE THREAD

**Issue by hchaudhari73** [hchaudhari73/goAuth#1]
I am testing this in Postman, when I send a get method for base url "/", it is setting a csrf token. But when I am querying "/login" with, I have to manually add a header for {"X-CSRF-TOKEN": token_value}. I am getting token value while quering "/".

**Comment by pkgmain** [comment]
For ant HTTP method other than `GET`, gorilla/csrf expects `x-csrf-token` in header or `gorilla.csrf.Token` in Form Fields. Your `/login` is a `POST` request, thats why it fails with `403 Forbidden` error. Check below screenshot from `gorilla/csrf` [example](https://github.com/gorilla/csrf#html-forms).

![Screen Shot 2021-08-08 at 11 12 25 AM](https://user-images.githubusercontent.com/5474893/128641563-50c3c901-faf0-4ea2-95a0-f92cd2131106.png)

**Comment by hchaudhari73** [comment]
Thanks @acodeb for you help, I have solved that issue and commited the changes, take a look and let me know if anything can be done to make it better.
